_target_: awesome_nlp.replica.in_context.retriever.bm25_retriever.BM25Retriever

num_ice: ${retrieve_ice}
num_candidates: ${num_candidates}
output_file: ${retrieved_file}    # used to store retrieved index
overwrite_cache: false

dataset_reader:
  _target_: awesome_nlp.replica.in_context.dataset_readers.retriever_dsr.RetrieverDatasetReader
  task_name: ${task_name}
  model_name: ${sentence_transformer}
  field: q                      # here no use
  dataset_split: validation     # some tasks do not have public test set, so we use validation set here
  dataset_path: null            # here set to null so do not do deduplication
  ds_size: null
  cache_dir: ${cache_dir}

index_reader:
  _target_: awesome_nlp.replica.in_context.dataset_readers.retriever_dsr.RetrieverDatasetReader
  task_name: ${task_name}
  model_name: ${sentence_transformer}
  field: q                      # retriever use question field to compute similarities
  dataset_split: train          # index_reader use train split
  dataset_path: ${index_file}   # used to store processed index dataset
  ds_size: null
  cache_dir: ${cache_dir}
